# Generated by Django 3.1.6 on 2021-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210706_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchymodel',
            name='parent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_desc',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
