# Generated by Django 3.1.6 on 2021-07-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210706_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_pic',
            field=models.ImageField(blank=True, null=True, upload_to='productmage'),
        ),
    ]
